project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    logo: gis-cert-2.jpg
    contents:
      - section: "ArcGIS Pro Installation"
        contents: install/*

format:
  html:
    css: styles.css
    toc: true

editor: visual

