project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

